name: CI

# tigger é a mudança na branch main
# Determinar as branches ou eventos que acionam a execução da pipeline.
on:
  push:
    branches:
      - main
      - develop
# executado após o on (trigger), Configurar as etapas de construção e implantação do projeto.
jobs:
  build:
    name: "Build and push"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [16, 18]
        # boa utilização em projetos frontend

    steps:
      # entra no repo, por isso dessa action
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: "npm"
          # caso seja monorepo tem que definir o path para ele achar o yarn.lock por ex
      - run: npm ci
      - run: npm test
      # daria para plugar um sonar aqui por ex

      # o name é o nome que aparece na execução do job, e pode ser qualquer coisa
      # o run é o comando que vai executar
      # o run pode ser um script ou um comando direto
      - name: Generate tag
        run: |
          SHA=$(echo $GITHUB_SHA | head -c7)
          echo "sha=$SHA" >> $GITHUB_OUTPUT

      - name: Build docker image
        run: docker build -t devops.ci.api:latest .
