name: CI

# tigger é a mudança na branch main
on:
  push:
    branches:
      - main
# executado após o on (trigger)
jobs:
  build:
    name: "Build and push"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
